### ISSUE TITLE
Migrate Node-RED automations back to Home Assistant

### ISSUE THREAD

**Issue by bjw-s** [bjw-s/hass-config#2]
With the enhanced automation features in Home Assistant it is now viable to move some? all? automations back from node-red to Home Assistant

**Comment by carpenike** [comment]
Curious what your reasons are for considering leaving Node Red?

**Comment by bjw-s** [comment]
I had some occurrences where NR somehow lost connection with hass. Plus I kept forgetting to commit my changes to the NR repo 😅 Had some serious dataloss there, which prompted me to see if I could consolidate in hass again. 

In recent hass versions their automation engine apparently gained some more powerful features that weren't possible before, so wanting to play around with that made 1+1=2 I guess.
